on: [push]
jobs:
  Deploy-to-PyCob:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: List files
      run: |
        ls -lrt
    - name: Install dependencies and Run pycob.deploy
      run: |
        python -m pip install --upgrade pip
        pip install pycob
        ls -lrt
        python -m pycob.deploy ${{ secrets.PYCOB_API_KEY }}
