name: Deploy App to PyCob Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: app
    - name: Install dependencies
      run: cd app && make venv
    - name: Deploy app
      run: cd app && PYCOB_API_KEY=${{ secrets.PYCOB_API_KEY }} make deploy
